// Generated by dia2code
#ifndef STATE__AELEMENTALLOC__H
#define STATE__AELEMENTALLOC__H


namespace state {
  class Element;
}

namespace state {

  /// class AElementAlloc - 
  class AElementAlloc {
    // Operations
  public:
    virtual AElementAlloc () = 0;
    virtual Element* newInstance () = 0;
    // Setters and Getters
  };

};

#endif
