// Generated by dia2code
#ifndef STATE__BATIMENT__H
#define STATE__BATIMENT__H


namespace state {
  class StaticElement;
}

#include "BatimentTypeId.h"
#include "StaticElement.h"

namespace state {

  /// class Batiment - 
  class Batiment : public state::StaticElement {
    // Associations
    state::BatimentTypeId batimentTypeId;
    // Attributes
  private:
    int capture;
    // Operations
  public:
    Batiment (BatimentTypeId id);
    ~Batiment ();
    bool const isChampdebataille ();
    TypeId const getTypeId ();
    int const getCapture ();
    void setCapture (int capture);
    // Setters and Getters
    BatimentTypeId getBatimentTypeId() const;
    void setBatimentTypeId(BatimentTypeId batimentTypeId);
  };

};

#endif
