// Generated by dia2code
#ifndef STATE__BATIMENT__H
#define STATE__BATIMENT__H


namespace state {
  class StaticElement;
}

#include "BatimentTypeId.h"
#include "TypeId.h"
#include "StaticElement.h"

namespace state {

  /// class Batiment - 
  class Batiment : public state::StaticElement {
    // Associations
    state::BatimentTypeId batimentTypeId;
    // Attributes
  private:
    int capture;
  protected:
    int pdv;
    // Operations
  public:
    Batiment ();
    Batiment (BatimentTypeId id);
    ~Batiment ();
    bool isChampdebataille () const;
    TypeId getTypeId () const;
    int getCapture () const;
    void setCapture (int capture);
    // Setters and Getters
    BatimentTypeId getBatimentTypeId() const;
    void setBatimentTypeId(BatimentTypeId batimentTypeId);
    int getPdv() const;
    void setPdv(int pdv);
  };

};

#endif
