// Generated by dia2code
#ifndef STATE__BATIMENTTYPEID__H
#define STATE__BATIMENTTYPEID__H


namespace state {

  enum BatimentTypeId {
    QGROUGE     = 0,
    CASERNEROUGE     = 1,
    APPARTROUGE     = 2,
    QGBLEU     = 3,
    CASERNEBLEU     = 4,
    APPARTBLEU     = 5
  };

};

#endif
