// Generated by dia2code
#ifndef STATE__CHAMPDEBATAILLE__H
#define STATE__CHAMPDEBATAILLE__H


namespace state {
  class StaticElement;
}

#include "ChampdebatailleTypeId.h"
#include "StaticElement.h"

namespace state {

  /// class Champdebataille - 
  class Champdebataille : public state::StaticElement {
    // Associations
    state::ChampdebatailleTypeId champdeBatailleType;
    // Operations
  public:
    Champdebataille ();
    Champdebataille (ChampdebatailleTypeId id);
    ~Champdebataille ();
    bool const isChampdebataille ();
    TypeId const getTypeId ();
    // Setters and Getters
    ChampdebatailleTypeId getChampdeBatailleType() const;
    void setChampdeBatailleType(ChampdebatailleTypeId champdeBatailleType);
  };

};

#endif
