// Generated by dia2code
#ifndef STATE__CHAMPDEBATAILLE__H
#define STATE__CHAMPDEBATAILLE__H


namespace state {
  class Element;
  class StaticElement;
}

#include "ChampdebatailleTypeId.h"
#include "StaticElement.h"

namespace state {

  /// class Champdebataille - 
  class Champdebataille : public state::StaticElement {
    // Associations
    // Operations
  public:
    Champdebataille (ChampdebatailleTypeId id);
    ~Champdebataille ();
    int const diffMap ();
    TypeId const getTypeId ();
    bool const equals (const Element& other);
    bool const isStatic ();
    // Setters and Getters
  };

};

#endif
