// Generated by dia2code
#ifndef STATE__CHAMPDEBATAILLETYPEID__H
#define STATE__CHAMPDEBATAILLETYPEID__H


namespace state {

  enum ChampdebatailleTypeId {
    HERBE     = 0,
    ROUTE     = 1,
    SABLE1     = 2,
    SABLE2     = 3,
    EAU     = 4,
    MONTAGNE     = 5
  };

};

#endif
