// Generated by dia2code
#ifndef STATE__CHAMPDEBATAILLETYPEID__H
#define STATE__CHAMPDEBATAILLETYPEID__H


namespace state {

  enum ChampdebatailleTypeId {
    HERBE     = 0,
    ROUTE     = 1,
    SABLE     = 2,
    EAU     = 3,
    ROCHER     = 4
  };

};

#endif
