// Generated by dia2code
#ifndef STATE__ELEMENTALLOC__H
#define STATE__ELEMENTALLOC__H


namespace state {

  /// class ElementAlloc - 
  class ElementAlloc {
    // Attributes
  public:
     id;
    // Setters and Getters
  };

};

#endif
