// Generated by dia2code
#ifndef STATE__ELEMENTFACTORY__H
#define STATE__ELEMENTFACTORY__H

#include <map>

namespace state {
  class AElementAlloc;
  class ElementFactory;
}

namespace state {

  /// class ElementFactory - 
  class ElementFactory {
    // Attributes
  public:
    std::map<int,AElementAlloc*> list;
    // Operations
  public:
    ElementFactory ();
    Element* const newinstance (int id);
    void registerType (int id, AElementAlloc* a);
    ElementFactory* createDefault ();
    // Setters and Getters
  };

};

#endif
