// Generated by dia2code
#ifndef STATE__ELEMENTCHARS__H
#define STATE__ELEMENTCHARS__H


namespace state {
  class Element;
  class ElementTab;
}

#include "ElementTab.h"

namespace state {

  /// class ElementChars - 
  class ElementChars : public state::ElementTab {
    // Operations
  public:
    ElementChars ();
    void ElementToCarte (const state::Element& e);
    // Setters and Getters
  };

};

#endif
