// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H


namespace state {
  class ElementTab;
}

#include "ElementTab.h"

namespace state {

  /// class Element - 
  class Element {
    // Associations
    // Operations
  public:
    Element ( );
    ~Element ();
    const getTypeId ();
    bool const isStatic ();
    // Setters and Getters
  };

};

#endif
