// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H


namespace state {
  class ElementTab;
}

#include "TypeId.h"
#include "ElementTab.h"

namespace state {

  /// class Element - 
  class Element {
    // Associations
    state::TypeId* typeId;
    // Operations
  public:
    Element ( );
    ~Element ();
    virtual TypeId const getTypeId () = 0;
    bool const isStatic ();
    // Setters and Getters
    void setTypeId(TypeId typeId);
  };

};

#endif
