// Generated by dia2code
#ifndef STATE__ELEMENTCHARS__H
#define STATE__ELEMENTCHARS__H

#include <stdlib.h>

namespace state {
  class ElementTab;
}

#include "ElementTab.h"

namespace state {

  /// class ElementChars - 
  class ElementChars : public state::ElementTab {
    // Operations
  public:
    ElementChars ();
    void setWidth (size_t width);
    void setHeight (size_t height);
    // Setters and Getters
  };

};

#endif
