// Generated by dia2code
#ifndef STATE__ELEMENTTAB__H
#define STATE__ELEMENTTAB__H

#include <stdlib.h>
#include <vector>
#include <memory>

namespace state {
  class Element;
}

namespace state {

  /// class ElementTab - 
  class ElementTab {
    // Attributes
  private:
    size_t width;
    size_t height;
    std::vector<std::unique_ptr<Element> > list;
    // Operations
  public:
    ElementTab ();
    ElementTab (size_t width, size_t height);
    ~ElementTab ();
    size_t getWidth ();
    size_t getHeight ();
    Element* const getElement (int i, int j);
    void setElement (Element* e);
    int sizeList ();
    void chgList (int i, Element* e);
    void chgList2 (int i, int j);
    // Setters and Getters
  };

};

#endif
