// Generated by dia2code
#ifndef STATE__INFANTERIE__H
#define STATE__INFANTERIE__H


namespace state {
  class MobileElement;
}

#include "MobileElement.h"
#include "InfanterieTypeId.h"

namespace state {

  /// class Infanterie - 
  class Infanterie : public state::MobileElement {
    // Associations
    // Operations
  public:
    Infanterie ();
    ~Infanterie ();
    int diffUnite ();
    TypeId const getTypeId ();
    // Setters and Getters
  };

};

#endif
