// Generated by dia2code
#ifndef STATE__INFANTERIETYPEID__H
#define STATE__INFANTERIETYPEID__H


namespace state {

  enum InfanterieTypeId {
    MVTATTENTE     = 0,
    MVTFINI     = 1,
    CAPTURE     = 2
  };

};

#endif
