// Generated by dia2code
#ifndef STATE__JOUEUR__H
#define STATE__JOUEUR__H

#include <vector>
#include <memory>

namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class Joueur - 
  class Joueur {
    // Associations
    // Attributes
  protected:
    std::vector<std::unique_ptr<Element> > listelemnt;
    // Operations
  public:
    void setElement (Element* e);
    Element* const getElement (int i);
    Joueur ();
    // Setters and Getters
    const std::vector<std::unique_ptr<Element> >& getListelemnt() const;
    void setListelemnt(const std::vector<std::unique_ptr<Element> >& listelemnt);
  };

};

#endif
