// Generated by dia2code
#ifndef STATE__MOBILEELEMENT__H
#define STATE__MOBILEELEMENT__H


namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class MobileElement - 
  class MobileElement : public state::Element {
    // Attributes
  protected:
    int position;
    int pdv;
    int mouvement;
    int defense;
    int attaque;
    // Operations
  public:
    MobileElement ( );
    ~MobileElement ();
    virtual int diffUnite () = 0;
    virtual bool const isStatic () = 0;
    void setposition (int position);
    int getposition ();
    int getpdv ();
    void setpdv (int pdv);
    int getmvt (int mvt);
    void setmvt (int mvt);
    int getdef ();
    void setdef (int def);
    int getatq ();
    void setatq (int atq);
    // Setters and Getters
    int getPosition() const;
    void setPosition(int position);
    int getPdv() const;
    void setPdv(int pdv);
    int getMouvement() const;
    void setMouvement(int mouvement);
    int getDefense() const;
    void setDefense(int defense);
    int getAttaque() const;
    void setAttaque(int attaque);
  };

};

#endif
