// Generated by dia2code
#ifndef STATE__STATICELEMENT__H
#define STATE__STATICELEMENT__H


namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class StaticElement - 
  class StaticElement : public state::Element {
    // Operations
  public:
    StaticElement ();
    ~StaticElement ();
    bool const isStatic ();
    virtual int const diffMap () = 0;
    // Setters and Getters
  };

};

#endif
