// Generated by dia2code
#ifndef STATE__TYPEID__H
#define STATE__TYPEID__H


namespace state {

  enum TypeId {
    CHAMPSDEBATAILLE     = 0,
    BATIMENT     = 1,
    INFANTERIE     = 2,
    HELI     = 3,
    TANK     = 4
  };

};

#endif
