// Generated by dia2code
#ifndef RENDER__LAYER__H
#define RENDER__LAYER__H

#include <memory>

namespace render {
  class Surface;
  class TileSet;
};
namespace state {
  class State;
  class ElementChars;
  class ElementTab;
}

#include "Surface.h"
#include "TileSet.h"
#include "state/State.h"
#include "state/ElementChars.h"
#include "state/ElementTab.h"

namespace render {

  /// class Layer - 
  class Layer {
    // Associations
    // Attributes
  public:
    std::unique_ptr<Surface> surface;
    std::unique_ptr<Surface> surfaceplayer;
    std::shared_ptr<TileSet> tilesetChars;
  private:
    const state::State& state;
  protected:
    std::shared_ptr<TileSet> tileset;
    // Operations
  public:
    Layer (const state::State& state);
    void initRandMap ();
    void initSurface ();
    // Setters and Getters
    const std::shared_ptr<TileSet>& getTileset() const;
    void setTileset(const std::shared_ptr<TileSet>& tileset);
  };

};

#endif
