// Generated by dia2code
#ifndef RENDER__RENDER__H
#define RENDER__RENDER__H


namespace sf {
  class Transformable;
  class Drawable;
}


namespace render {

  /// class Render - 
  class Render : public sf::Transformable, public sf::Drawable {
    // Operations
  public:
    bool load (tileset const std::string&, tileSize sf::Vector2u, tiles const int*, width unsigned int, height unsigned int);
    // Setters and Getters
  };

};

#endif
