// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H

#include <vector>
#include <memory>

namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "engine/Command.h"

namespace ai {

  /// class AI - 
  class AI {
    // Operations
  public:
    void InfanterieCommands (const state::State& state, int i, std::vector<std::unique_ptr<engine::Command> >& list0);
    void HeliCommands (const state::State& state, int i, std::vector<std::unique_ptr<engine::Command> >& list1);
    void TankCommands (const state::State& state, int i, std::vector<std::unique_ptr<engine::Command> >& list2);
    // Setters and Getters
  };

};

#endif
