// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H

#include <vector>
#include <memory>

namespace engine {
  class Command;
};
namespace state {
  class State;
}

#include "engine/Command.h"

namespace ai {

  /// class AI - 
  class AI {
    // Operations
  public:
    void listCommands (std::vector<std::unique_ptr<engine::Command> >& list, const state::State& state, int caractere);
    // Setters and Getters
  };

};

#endif
