// Generated by dia2code
#ifndef AI__DIRECTION__H
#define AI__DIRECTION__H


namespace ai {

  enum Direction {
    AUCUN     = 0,
    HAUT     = 1,
    BAS     = 2,
    GAUCHE     = 3,
    DROITE     = 4
  };

};

#endif
