// Generated by dia2code
#ifndef AI__HEURISTICAI__H
#define AI__HEURISTICAI__H


namespace ai {
  class Pathmap;
};
namespace engine {
  class Engine;
};
namespace ai {
  class AI;
}

#include "Pathmap.h"
#include "AI.h"

namespace ai {

  /// class HeuristicAI - 
  class HeuristicAI : public ai::AI {
    // Associations
    // Attributes
  public:
    Pathmap infmap;
    // Operations
  public:
    void run (int joueur, engine::Engine& engine);
    HeuristicAI ();
    const Pathmap& getInfmap (engine::Engine& engine, int joueur) const;
    // Setters and Getters
  };

};

#endif
