// Generated by dia2code
#ifndef AI__HEURISTICAI__H
#define AI__HEURISTICAI__H


namespace ai {
  class Pathinf;
  class Pathheli;
  class Pathtank;
};
namespace engine {
  class Engine;
};
namespace ai {
  class Pathmap;
  class AI;
}

#include "Pathinf.h"
#include "Pathheli.h"
#include "Pathtank.h"
#include "AI.h"
#include "Pathmap.h"

namespace ai {

  /// class HeuristicAI - 
  class HeuristicAI : public ai::AI {
    // Associations
    // Attributes
  public:
    Pathinf infmap;
    Pathheli helimap;
    Pathtank tankmap;
    // Operations
  public:
    void run (int joueur, engine::Engine& engine);
    HeuristicAI ();
    Pathmap& getInfmap (engine::Engine& engine, int joueur);
    Pathmap& getTankmap (engine::Engine& engine, int joueur);
    Pathmap& getHelimap (engine::Engine& engine, int joueur);
    void setInfmap (engine::Engine& engine, int joueur);
    void setTankmap (engine::Engine& engine, int joueur);
    void setHelimap (engine::Engine& engine, int joueur);
    // Setters and Getters
  };

};

#endif
