// Generated by dia2code
#ifndef AI__PATHINF__H
#define AI__PATHINF__H


namespace state {
  class ElementTab;
};
namespace ai {
  class Pathmap;
}

#include "Pathmap.h"

namespace ai {

  /// class Pathinf - 
  class Pathinf : public ai::Pathmap {
    // Operations
  public:
    void init (state::ElementTab& grid);
    // Setters and Getters
  };

};

#endif
