// Generated by dia2code
#ifndef AI__PATHHELI__H
#define AI__PATHHELI__H


namespace state {
  class ElementTab;
};
namespace ai {
  class Pathmap;
}

#include "Pathmap.h"

namespace ai {

  /// class Pathheli - 
  class Pathheli : public ai::Pathmap {
    // Operations
  public:
    void init (state::ElementTab& grid);
    // Setters and Getters
  };

};

#endif
