// Generated by dia2code
#ifndef ENGINE__ATTAQUECHARCOMMAND__H
#define ENGINE__ATTAQUECHARCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class AttaqueCharCommand - 
  class AttaqueCharCommand : public engine::Command {
    // Attributes
  private:
    int x1;
    int y1;
    int x2;
    int y2;
    // Operations
  public:
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    AttaqueCharCommand (int x1, int y1, int x2, int y2);
    // Setters and Getters
  };

};

#endif
