// Generated by dia2code
#ifndef ENGINE__ATTAQUECHARCOMMAND__H
#define ENGINE__ATTAQUECHARCOMMAND__H


namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class attaqueCharcommand - 
  class attaqueCharcommand : public engine::Command {
    // Operations
  public:
    CommandTypeId const getTypeId ();
    void execute (state::state& state);
    // Setters and Getters
  };

};

#endif
