// Generated by dia2code
#ifndef ENGINE__ATTAQUECHARACTION__H
#define ENGINE__ATTAQUECHARACTION__H


namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class AttaqueCharAction - 
  class AttaqueCharAction : public engine::Action {
    // Attributes
  public:
    int x1;
    int y1;
    int x2;
    int y2;
    // Operations
  public:
    void apply (state::State& state);
    void undo (state::State& state);
    AttaqueCharAction (int x1, int y1, int x2, int y2);
    // Setters and Getters
  };

};

#endif
