// Generated by dia2code
#ifndef ENGINE__ATTAQUECHARCOMMAND__H
#define ENGINE__ATTAQUECHARCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class AttaqueCharcommand - 
  class AttaqueCharcommand : public engine::Command {
    // Operations
  public:
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    // Setters and Getters
  };

};

#endif
