// Generated by dia2code
#ifndef ENGINE__CAPTURAPPARTACTION__H
#define ENGINE__CAPTURAPPARTACTION__H


namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class CapturAppartAction - 
  class CapturAppartAction : public engine::Action {
    // Attributes
  private:
    int x;
    int y;
    int joueur;
    // Operations
  public:
    void apply (state::State& state);
    void undo (state::State& state);
    CapturAppartAction (int x, int y, int joueur);
    // Setters and Getters
  };

};

#endif
