// Generated by dia2code
#ifndef ENGINE__CAPTURCASERNEACTION__H
#define ENGINE__CAPTURCASERNEACTION__H


namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class CapturCaserneAction - 
  class CapturCaserneAction : public engine::Action {
    // Attributes
  public:
    int x;
    int y;
    int joueur;
    // Operations
  public:
    void apply (state::State& state);
    void undo (state::State& state);
    CapturCaserneAction (int x, int y, int joueur);
    // Setters and Getters
  };

};

#endif
