// Generated by dia2code
#ifndef ENGINE__CAPTURQGACTION__H
#define ENGINE__CAPTURQGACTION__H


namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class CapturQGAction - 
  class CapturQGAction : public engine::Action {
    // Attributes
  public:
    int x;
    int y;
    int joueur;
    // Operations
  public:
    void apply (state::State& state);
    void undo (state::State& state);
    CapturQGAction (int x, int y, int joueur);
    // Setters and Getters
  };

};

#endif
