// Generated by dia2code
#ifndef ENGINE__CAPTURCHARACTION__H
#define ENGINE__CAPTURCHARACTION__H


namespace state {
  class State;
}

#include "state/TypeId.h"

namespace engine {

  /// class CapturCharAction - 
  class CapturCharAction {
    // Attributes
  public:
    int x;
    int y;
    state::TypeId elementId;
    int joueur;
    // Operations
  public:
    void apply (state::State& state);
    void undo (state::State& state);
    KillCharAction (int x, int y, state::TypeId elementId, int joueur);
    // Setters and Getters
  };

};

#endif
