// Generated by dia2code
#ifndef ENGINE__COMMANDTYPEID__H
#define ENGINE__COMMANDTYPEID__H


namespace engine {

  enum CommandTypeId {
    LOAD     = 1,
    CAPTUR     = 2,
    MOVE     = 3,
    ATTAQUE     = 4
  };

};

#endif
