// Generated by dia2code
#ifndef ENGINE__CREATECHARCOMMAND__H
#define ENGINE__CREATECHARCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "state/TypeId.h"
#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class CreateCharCommand - 
  class CreateCharCommand : public engine::Command {
    // Associations
    // Attributes
  public:
    int x;
    state::TypeId d;
    int joueur;
    int y;
    // Operations
  public:
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    CreateCharCommand (state::TypeId d, int joueur);
    // Setters and Getters
  };

};

#endif
