// Generated by dia2code
#ifndef ENGINE__CREATECHARCOMMAND__H
#define ENGINE__CREATECHARCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "state/TypeId.h"
#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class CreateCharCommand - 
  class CreateCharCommand : public engine::Command {
    // Associations
    // Attributes
  private:
    state::TypeId elementId;
    int x;
    int y;
    int joueur;
    // Operations
  public:
    CreateCharCommand (state::TypeId elementId, int x, int y, int joueur);
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    // Setters and Getters
  };

};

#endif
