// Generated by dia2code
#ifndef ENGINE__CREATECHARCOMMAND__H
#define ENGINE__CREATECHARCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "state/TypeId.h"
#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class CreateCharCommand - 
  class CreateCharCommand : public engine::Command {
    // Associations
    // Attributes
  public:
    int i;
    state::TypeId d;
    // Operations
  public:
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    CreateCharCommand (int i, state::TypeId d);
    // Setters and Getters
  };

};

#endif
