// Generated by dia2code
#ifndef ENGINE__CREATEINFANTERIEACTION__H
#define ENGINE__CREATEINFANTERIEACTION__H


namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"
#include "state/TypeId.h"

namespace engine {

  /// class CreateInfanterieAction - 
  class CreateInfanterieAction : public engine::Action {
    // Associations
    // Attributes
  public:
    int x;
    int y;
    int joueur;
    // Operations
  public:
    void apply (state::State& state);
    void undo (state::State& state);
    CreateInfanterieAction (int x, int y, int joueur);
    // Setters and Getters
  };

};

#endif
