// Generated by dia2code
#ifndef ENGINE__EARNMONEY__H
#define ENGINE__EARNMONEY__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class EarnMoney - 
  class EarnMoney : public engine::Command {
    // Operations
  public:
    EarnMoney ();
    void execute (state::State& state);
    CommandTypeId getTypeId () const;
    // Setters and Getters
  };

};

#endif
