// Generated by dia2code
#ifndef ENGINE__KILLHELIACTION__H
#define ENGINE__KILLHELIACTION__H


namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class KillHeliAction - 
  class KillHeliAction : public engine::Action {
    // Attributes
  private:
    int x;
    int y;
    int joueur;
    // Operations
  public:
    void apply (state::State& state);
    void undo (state::State& state);
    KillHeliAction (int x, int y, int joueur);
    // Setters and Getters
  };

};

#endif
