// Generated by dia2code
#ifndef ENGINE__KILLINFANTERIEACTION__H
#define ENGINE__KILLINFANTERIEACTION__H


namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "state/TypeId.h"
#include "Action.h"

namespace engine {

  /// class KillInfanterieAction - 
  class KillInfanterieAction : public engine::Action {
    // Attributes
  public:
    int x;
    int y;
    state::TypeId elementId;
    int joueur;
    // Operations
  public:
    void apply (state::State& state);
    void undo (state::State& state);
    KillInfanterieAction (int x, int y, state::TypeId elementId, int joueur);
    // Setters and Getters
  };

};

#endif
