// Generated by dia2code
#ifndef ENGINE__LOADCOMMAND__H
#define ENGINE__LOADCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class Loadcommand - 
  class Loadcommand : public engine::Command {
    // Operations
  public:
    commandTypeId const getTypeId ();
    void execute (state::State& state);
    // Setters and Getters
  };

};

#endif
