// Generated by dia2code
#ifndef ENGINE__LOADCOMMAND__H
#define ENGINE__LOADCOMMAND__H

#include <string>
#include <stack>
#include <memory>
#include <json/json.h>

namespace engine {
  class Action;
};
namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Action.h"
#include "Command.h"

namespace engine {

  /// class LoadCommand - 
  class LoadCommand : public engine::Command {
    // Attributes
  protected:
    std::string filename;
    // Operations
  public:
    CommandTypeId getTypeId () const;
    void execute (std::stack<std::shared_ptr<Action>>& actions, state::State& state);
    LoadCommand (const char* f);
    void serialise (Json::Value& out) const;
    // Setters and Getters
    const std::string& getFilename() const;
    void setFilename(const std::string& filename);
  };

};

#endif
