// Generated by dia2code
#ifndef ENGINE__LOADCOMMAND__H
#define ENGINE__LOADCOMMAND__H

#include <string>

namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class LoadCommand - 
  class LoadCommand : public engine::Command {
    // Attributes
  protected:
    std::string filename;
    // Operations
  public:
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    LoadCommand (const char* f);
    // Setters and Getters
    const std::string& getFilename() const;
    void setFilename(const std::string& filename);
  };

};

#endif
