// Generated by dia2code
#ifndef ENGINE__MOVECHARCOMMAND__H
#define ENGINE__MOVECHARCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class MoveCharCommand - 
  class MoveCharCommand : public engine::Command {
    // Attributes
  public:
    int x1;
    int y1;
    int x2;
    int y2;
    // Operations
  public:
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    MoveCharCommand (int x1, int y1, int x2, int y2);
    // Setters and Getters
  };

};

#endif
