// Generated by dia2code
#ifndef ENGINE__MOVECHARACTION__H
#define ENGINE__MOVECHARACTION__H


namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class MoveCharAction - 
  class MoveCharAction : public engine::Action {
    // Attributes
  public:
    int x1;
    int y1;
    int x2;
    int y2;
    // Operations
  public:
    void apply (state::State& state);
    void undo (state::State& state);
    MoveCharAction (int x1, int y1, int x2, int y2);
    // Setters and Getters
  };

};

#endif
