// Generated by dia2code
#ifndef ENGINE__MOVECHARCOMMAND__H
#define ENGINE__MOVECHARCOMMAND__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class MovecharCommand - 
  class MovecharCommand : public engine::Command {
    // Operations
  public:
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    void bouger (state::State& state, int i1, int j1, int i2, int j2);
    // Setters and Getters
  };

};

#endif
