// Generated by dia2code
#ifndef SERVER__PLAYER__H
#define SERVER__PLAYER__H

#include <string>

namespace server {

  /// class Player - 
  class Player {
    // Attributes
  public:
    std::string name;
    bool = true free;
    // Operations
  public:
    User (string name, int age);
    // Setters and Getters
  };

};

#endif
