// Generated by dia2code
#ifndef __ENGINE__H
#define __ENGINE__H

#include "engine/CommandTypeId.h"
#include "engine/Action.h"
#include "engine/Command.h"
#include "engine/LoadCommand.h"
#include "engine/MoveCharCommand.h"
#include "engine/AttaqueCharCommand.h"
#include "engine/Engine.h"
#include "engine/CapturCharCommand.h"
#include "engine/CreateCharCommand.h"
#include "engine/EarnMoney.h"
#include "engine/MoveCharAction.h"
#include "engine/CreateCharAction.h"
#include "engine/KillCharAction.h"
#include "engine/EarnMoneyAction.h"
#include "engine/AttaqueCharAction.h"
#include "engine/CapturCharAction.h"
#endif
