// Generated by dia2code
#ifndef __ENGINE__H
#define __ENGINE__H

#include "engine/CommandTypeId.h"
#include "engine/Action.h"
#include "engine/Command.h"
#include "engine/LoadCommand.h"
#include "engine/MoveCharCommand.h"
#include "engine/AttaqueCharCommand.h"
#include "engine/Engine.h"
#include "engine/CapturCharCommand.h"
#include "engine/CreateCharCommand.h"
#include "engine/EarnMoney.h"
#include "engine/MoveCharAction.h"
#include "engine/CreateInfanterieAction.h"
#include "engine/KillInfanterieAction.h"
#include "engine/EarnMoneyAction.h"
#include "engine/AttaqueCharAction.h"
#include "engine/CreateTankAction.h"
#include "engine/CreateHeliAction.h"
#include "engine/KillTankAction.h"
#include "engine/KillHeliAction.h"
#include "engine/CapturQGAction.h"
#include "engine/CapturAppartAction.h"
#include "engine/CapturCaserneAction.h"
#endif
