// Generated by dia2code
#ifndef __STATE__H
#define __STATE__H

#include "state/TypeId.h"
#include "state/ElementTab.h"
#include "state/Element.h"
#include "state/StaticElement.h"
#include "state/ChampdebatailleTypeId.h"
#include "state/Champdebataille.h"
#include "state/BatimentTypeId.h"
#include "state/Batiment.h"
#include "state/MobileElement.h"
#include "state/InfanterieTypeId.h"
#include "state/Infanterie.h"
#include "state/HeliTypeId.h"
#include "state/Heli.h"
#include "state/TankTypeId.h"
#include "state/Tank.h"
#include "state/ElementChars.h"
#include "state/State.h"
#include "state/AElementAlloc.h"
#include "state/ElementAlloc.h"
#endif
