// Generated by dia2code
#ifndef CLIENT__CLIENT__H
#define CLIENT__CLIENT__H


namespace engine {
  class Engine;
};
namespace ai {
  class HeuristicAI;
}

#include "engine/Engine.h"
#include "ai/HeuristicAI.h"

namespace client {

  /// class Client - 
  class Client {
    // Associations
    // Attributes
  public:
    engine::Engine engine;
    ai::HeuristicAI heuristic;
    // Operations
  public:
    Client ();
    void engineUdapting ();
    void engineUdapted ();
    void run ();
    // Setters and Getters
  };

};

#endif
