// Generated by dia2code
#ifndef __RENDER__H
#define __RENDER__H

#include "render/Tile.h"
#include "render/TileSet.h"
#include "render/GridTileSet.h"
#include "render/Surface.h"
#include "render/Layer.h"
#include "render/CharsTileSet.h"
#endif
